module.exports = {
    RECEIVE_CONTACTS: 'RECEIVE_CONTACTS',
    SAVE_CONTACT: 'SAVE_CONTACT',
    REMOVE_CONTACTS: 'REMOVE_CONTACTS',
    EDIT_CONTACTS: 'EDIT_CONTACTS',
    UPDATE_CONTACTS: 'UPDATE_CONTACTS'
}